language: go

# Skip the install step. Don't `go get` dependencies
install: skip

branches:
  only:
    - "master"
env:
  global:
    - GO111MODULE=on
    - RUN_ON_CI=true

script: skip

jobs:
  include:
    - stage: test
      name: "Build and unit-test with Go 1.12.x"
      go: 1.12.x
      script: make test-unit
    - stage: test
      name: "Build and unit-test with Go 1.13.x"
      go: 1.13.x
      script: make test-unit
    - stage: test
      name: "Hammer unit-test with Go 1.13.x"
      go: 1.13.x
      script: make test-hammer
    - stage: test
      name: "Code Quality Analysis"
      script: make test-lint
      go: 1.13.x
    - stage: test-integration
      name: "Integration testing on OSX"
      script: make test-integration
      os: osx
      go: 1.13.x
    - stage: test-integration
      name: "Integration testing on Linux"
      script: make test-integration
      os: linux
      go: 1.13.x
    - stage: test-integration
      name: "Integration testing on Windows"
      before_install:
        - export "BUILD_BINARY=$TRAVIS_BUILD_DIR/codeowners-validator"
      script:
        - go build -o codeowners-validator ./main.go
        - go test ./tests/integration/... -v -tags=integration
      os: windows
      go: 1.13.x
